# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mariodr/legion-docker:HTR-1.3

pipelines:
   default:
#    - step:
#        name: Compile prometeo
#        script: # Modify the commands below to build your repository.
#          - cd src
##          - make
#
#      - parallel:
         - step:
            name: Test Config
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/configTest/test.py -v

         - step:
            name: Test math_utils
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/mathUtilsTest/test.py -v

         - step:
            name: Test hdf_helper
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/hdfTest/test.py -v

         - step:
            name: Test mixtures
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/mixTest/test.py -v

         - step:
            name: Test geometry
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/geometryTest/test.py -v

         - step:
            name: Test metric
            script:
               - cd unitTests/metricTest
               - make -j
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./operatorsTest_Periodic.exec
               - ./operatorsTest_Staggered.exec
               - ./operatorsTest_Collocated.exec
               - ./metricTest_Periodic.exec

         - step:
            name: Test cfl
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/cflTest/test.py -v

         - step:
            name: Test chemistry
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/chemTest/test.py -v

         - step:
            name: Test variables
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/variablesTest/test.py -v

         - step:
            name: Test probe
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/probeTest/test.py -v

         - step:
            name: Test average
            script:
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - python3 unitTests/averageTest/test.py -v

